### ISSUE TITLE
Support for MySQL 8.x and MySQL 5.x alongside MariaDB

### ISSUE THREAD

**Issue by mburri** [sfa-siard/JdbcMySql#4]
Archiving the Nation example Database with MySQL 8.x breaks whit the following error:

```
java.sql.SQLException: Table country_languages has no columns!
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.getColumns(MetaDataFromDb.java:1251)
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.getTables(MetaDataFromDb.java:1330)
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.download(MetaDataFromDb.java:1390)
	at ch.admin.bar.siardsuite.database.DatabaseLoadTask.call(DatabaseLoadTask.java:51)
	at ch.admin.bar.siardsuite.database.DatabaseLoadTask.call(DatabaseLoadTask.java:24)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Service.java:727)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Service.java:726)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

But the table `country_languages` clealry has some columns.
Similar errors where experienced from other users: https://github.com/sfa-siard/SiardGui/issues/52

It also looks like it's not possible to connect to versions of MySQL 5.x at all!

MariaDB seems to be fine.

* [x] Setup the Nation Exmple DB in Docker containers for MySQL 8.x, MySQL 5.x and MariaDB (latest) for manual testing
* [x] Setup running integration tests for Maria DB with the nation example database
* [x] Setup the same tests - but with MySQL 8.x and MySql 5.x
* [x] Verify the issues

**Comment by sdbuehlmann** [comment]
Resolved through the following commits in JdbsMySql:
- [4f01bebbde0a588b69ce63ed2fc0bf3c12bab2fd](https://github.com/sfa-siard/JdbcMySql/commit/4f01bebbde0a588b69ce63ed2fc0bf3c12bab2fd)
- [e83150274e810a477c8170a7aef8e350c0bf4a03](https://github.com/sfa-siard/JdbcMySql/commit/e83150274e810a477c8170a7aef8e350c0bf4a03)
